Repository uchihanaruto9371/OnlineChess, pull requests merged in 2020-05, with the labels that each got.

#17 Feature/ux overhall
  application.py
  enter_message.py
  game.py
  game_test.py
  static/scripts/socketio.js
  templates/edit.html
  templates/index.html
  templates/lobby.html
  templates/login.html
Labels: enhancement

#18 Feature/styling-v3
  application.py
  enter_message.py
  static/scripts/socketio.js
  static/styling/lobby.css
  static/styling/style.css
  templates/edit.html
  templates/index.html
  templates/lobby.html
  templates/login.html
Labels: enhancement

#19 Feature/setting ci
  .travis.yml
  README.md
  game_test.py
  requirements.txt
  static/styling/lobby.css
  static/styling/style.css
Labels: Test, documentation

#20 Feature/readme style
  README.md
Labels: documentation
