Repository uchihanaruto9371/OnlineChess, pull requests merged in 2020-04, with the labels that each got.

#9 Feature/player lobbies
  application.py
  static/scripts/socketio.js
  templates/lobby.html
  test.txt
  wtform_fields.py
Labels: enhancement

#10 Feature/game implementation
  application.py
  game.py
  static/scripts/socketio.js
  static/styling/lobby.css
Labels: enhancement

#14 Feature/code structuring
  application.py
  game.py
  static/scripts/socketio.js
  static/styling/lobby.css
  templates/lobby.html
  test.txt
  wtform_fields.py
Labels: bug

#15 Feature/unit test web
  test.py
Labels: Test

#16 Feature/unit test game
  game_test.py
  test.py
Labels: Test
